// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS4EIqcTMalxGaZdvr0wARBiIC0XwvJ_8',
    appId: '1:24895774475:web:9badc7954e57bb297e8c0e',
    messagingSenderId: '24895774475',
    projectId: 'sikama-70f9c',
    authDomain: 'sikama-70f9c.firebaseapp.com',
    storageBucket: 'sikama-70f9c.appspot.com',
    measurementId: 'G-5EMKK2B604',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgsTGEJ2xSYUtSvYxUQGdhB55BXGAwb0w',
    appId: '1:24895774475:android:895a40ce256bbe667e8c0e',
    messagingSenderId: '24895774475',
    projectId: 'sikama-70f9c',
    storageBucket: 'sikama-70f9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxLw8vFBXlE1iz8FxalmEb67AelEkOetY',
    appId: '1:24895774475:ios:56d11b49617e10cd7e8c0e',
    messagingSenderId: '24895774475',
    projectId: 'sikama-70f9c',
    storageBucket: 'sikama-70f9c.appspot.com',
    iosClientId: '24895774475-82hd9f2tbm461cfcugm78j6ejjfpu619.apps.googleusercontent.com',
    iosBundleId: 'com.example.mage8',
  );
}
